// 与 src/assets/scss/_variables.scss 保持同步
export const BENTO_GRID_COLUMNS = 8
export const BENTO_GRID_COLUMNS_MOBILE = 4
export const BENTO_GRID_GAP = 10
export const BENTO_GRID_ROW_HEIGHT = 87.5
export const BENTO_GRID_WIDTH_DESKTOP = 700
export const BENTO_GRID_WIDTH_MOBILE = 350

export const BENTO_CELL_DESKTOP =
  (BENTO_GRID_WIDTH_DESKTOP - (BENTO_GRID_COLUMNS - 1) * BENTO_GRID_GAP) /
  BENTO_GRID_COLUMNS

export const BENTO_CELL_MOBILE =
  (BENTO_GRID_WIDTH_MOBILE - (BENTO_GRID_COLUMNS_MOBILE - 1) * BENTO_GRID_GAP) /
  BENTO_GRID_COLUMNS_MOBILE
